// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"goBack/ent/migrate"

	"goBack/ent/tn_bbs"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// TN_BBS is the client for interacting with the TN_BBS builders.
	TN_BBS *TNBBSClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.TN_BBS = NewTNBBSClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:    ctx,
		config: cfg,
		TN_BBS: NewTNBBSClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:    ctx,
		config: cfg,
		TN_BBS: NewTNBBSClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		TN_BBS.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.TN_BBS.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.TN_BBS.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *TNBBSMutation:
		return c.TN_BBS.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// TNBBSClient is a client for the TN_BBS schema.
type TNBBSClient struct {
	config
}

// NewTNBBSClient returns a client for the TN_BBS from the given config.
func NewTNBBSClient(c config) *TNBBSClient {
	return &TNBBSClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tn_bbs.Hooks(f(g(h())))`.
func (c *TNBBSClient) Use(hooks ...Hook) {
	c.hooks.TN_BBS = append(c.hooks.TN_BBS, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `tn_bbs.Intercept(f(g(h())))`.
func (c *TNBBSClient) Intercept(interceptors ...Interceptor) {
	c.inters.TN_BBS = append(c.inters.TN_BBS, interceptors...)
}

// Create returns a builder for creating a TN_BBS entity.
func (c *TNBBSClient) Create() *TNBBSCreate {
	mutation := newTNBBSMutation(c.config, OpCreate)
	return &TNBBSCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TN_BBS entities.
func (c *TNBBSClient) CreateBulk(builders ...*TNBBSCreate) *TNBBSCreateBulk {
	return &TNBBSCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TNBBSClient) MapCreateBulk(slice any, setFunc func(*TNBBSCreate, int)) *TNBBSCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TNBBSCreateBulk{err: fmt.Errorf("calling to TNBBSClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TNBBSCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TNBBSCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TN_BBS.
func (c *TNBBSClient) Update() *TNBBSUpdate {
	mutation := newTNBBSMutation(c.config, OpUpdate)
	return &TNBBSUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TNBBSClient) UpdateOne(tb *TN_BBS) *TNBBSUpdateOne {
	mutation := newTNBBSMutation(c.config, OpUpdateOne, withTN_BBS(tb))
	return &TNBBSUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TNBBSClient) UpdateOneID(id int) *TNBBSUpdateOne {
	mutation := newTNBBSMutation(c.config, OpUpdateOne, withTN_BBSID(id))
	return &TNBBSUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TN_BBS.
func (c *TNBBSClient) Delete() *TNBBSDelete {
	mutation := newTNBBSMutation(c.config, OpDelete)
	return &TNBBSDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TNBBSClient) DeleteOne(tb *TN_BBS) *TNBBSDeleteOne {
	return c.DeleteOneID(tb.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TNBBSClient) DeleteOneID(id int) *TNBBSDeleteOne {
	builder := c.Delete().Where(tn_bbs.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TNBBSDeleteOne{builder}
}

// Query returns a query builder for TN_BBS.
func (c *TNBBSClient) Query() *TNBBSQuery {
	return &TNBBSQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTNBBS},
		inters: c.Interceptors(),
	}
}

// Get returns a TN_BBS entity by its id.
func (c *TNBBSClient) Get(ctx context.Context, id int) (*TN_BBS, error) {
	return c.Query().Where(tn_bbs.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TNBBSClient) GetX(ctx context.Context, id int) *TN_BBS {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TNBBSClient) Hooks() []Hook {
	return c.hooks.TN_BBS
}

// Interceptors returns the client interceptors.
func (c *TNBBSClient) Interceptors() []Interceptor {
	return c.inters.TN_BBS
}

func (c *TNBBSClient) mutate(ctx context.Context, m *TNBBSMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TNBBSCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TNBBSUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TNBBSUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TNBBSDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TN_BBS mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		TN_BBS []ent.Hook
	}
	inters struct {
		TN_BBS []ent.Interceptor
	}
)
