// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"goBack/ent/predicate"
	"goBack/ent/tn_bbs"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeTNBBS = "TN_BBS"
)

// TNBBSMutation represents an operation that mutates the TN_BBS nodes in the graph.
type TNBBSMutation struct {
	config
	op            Op
	typ           string
	id            *int
	user_id       *string
	user_name     *string
	title         *string
	content       *string
	delect_yn     *string
	reg_date      *string
	udt_date      *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*TN_BBS, error)
	predicates    []predicate.TN_BBS
}

var _ ent.Mutation = (*TNBBSMutation)(nil)

// tnBBSOption allows management of the mutation configuration using functional options.
type tnBBSOption func(*TNBBSMutation)

// newTNBBSMutation creates new mutation for the TN_BBS entity.
func newTNBBSMutation(c config, op Op, opts ...tnBBSOption) *TNBBSMutation {
	m := &TNBBSMutation{
		config:        c,
		op:            op,
		typ:           TypeTNBBS,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withTN_BBSID sets the ID field of the mutation.
func withTN_BBSID(id int) tnBBSOption {
	return func(m *TNBBSMutation) {
		var (
			err   error
			once  sync.Once
			value *TN_BBS
		)
		m.oldValue = func(ctx context.Context) (*TN_BBS, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().TN_BBS.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withTN_BBS sets the old TN_BBS of the mutation.
func withTN_BBS(node *TN_BBS) tnBBSOption {
	return func(m *TNBBSMutation) {
		m.oldValue = func(context.Context) (*TN_BBS, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m TNBBSMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m TNBBSMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of TN_BBS entities.
func (m *TNBBSMutation) SetID(id int) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *TNBBSMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *TNBBSMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().TN_BBS.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetUserID sets the "user_id" field.
func (m *TNBBSMutation) SetUserID(s string) {
	m.user_id = &s
}

// UserID returns the value of the "user_id" field in the mutation.
func (m *TNBBSMutation) UserID() (r string, exists bool) {
	v := m.user_id
	if v == nil {
		return
	}
	return *v, true
}

// OldUserID returns the old "user_id" field's value of the TN_BBS entity.
// If the TN_BBS object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TNBBSMutation) OldUserID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUserID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUserID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserID: %w", err)
	}
	return oldValue.UserID, nil
}

// ResetUserID resets all changes to the "user_id" field.
func (m *TNBBSMutation) ResetUserID() {
	m.user_id = nil
}

// SetUserName sets the "user_name" field.
func (m *TNBBSMutation) SetUserName(s string) {
	m.user_name = &s
}

// UserName returns the value of the "user_name" field in the mutation.
func (m *TNBBSMutation) UserName() (r string, exists bool) {
	v := m.user_name
	if v == nil {
		return
	}
	return *v, true
}

// OldUserName returns the old "user_name" field's value of the TN_BBS entity.
// If the TN_BBS object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TNBBSMutation) OldUserName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUserName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUserName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserName: %w", err)
	}
	return oldValue.UserName, nil
}

// ResetUserName resets all changes to the "user_name" field.
func (m *TNBBSMutation) ResetUserName() {
	m.user_name = nil
}

// SetTitle sets the "title" field.
func (m *TNBBSMutation) SetTitle(s string) {
	m.title = &s
}

// Title returns the value of the "title" field in the mutation.
func (m *TNBBSMutation) Title() (r string, exists bool) {
	v := m.title
	if v == nil {
		return
	}
	return *v, true
}

// OldTitle returns the old "title" field's value of the TN_BBS entity.
// If the TN_BBS object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TNBBSMutation) OldTitle(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTitle is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTitle requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTitle: %w", err)
	}
	return oldValue.Title, nil
}

// ResetTitle resets all changes to the "title" field.
func (m *TNBBSMutation) ResetTitle() {
	m.title = nil
}

// SetContent sets the "content" field.
func (m *TNBBSMutation) SetContent(s string) {
	m.content = &s
}

// Content returns the value of the "content" field in the mutation.
func (m *TNBBSMutation) Content() (r string, exists bool) {
	v := m.content
	if v == nil {
		return
	}
	return *v, true
}

// OldContent returns the old "content" field's value of the TN_BBS entity.
// If the TN_BBS object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TNBBSMutation) OldContent(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldContent is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldContent requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldContent: %w", err)
	}
	return oldValue.Content, nil
}

// ResetContent resets all changes to the "content" field.
func (m *TNBBSMutation) ResetContent() {
	m.content = nil
}

// SetDelectYn sets the "delect_yn" field.
func (m *TNBBSMutation) SetDelectYn(s string) {
	m.delect_yn = &s
}

// DelectYn returns the value of the "delect_yn" field in the mutation.
func (m *TNBBSMutation) DelectYn() (r string, exists bool) {
	v := m.delect_yn
	if v == nil {
		return
	}
	return *v, true
}

// OldDelectYn returns the old "delect_yn" field's value of the TN_BBS entity.
// If the TN_BBS object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TNBBSMutation) OldDelectYn(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDelectYn is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDelectYn requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDelectYn: %w", err)
	}
	return oldValue.DelectYn, nil
}

// ResetDelectYn resets all changes to the "delect_yn" field.
func (m *TNBBSMutation) ResetDelectYn() {
	m.delect_yn = nil
}

// SetRegDate sets the "reg_date" field.
func (m *TNBBSMutation) SetRegDate(s string) {
	m.reg_date = &s
}

// RegDate returns the value of the "reg_date" field in the mutation.
func (m *TNBBSMutation) RegDate() (r string, exists bool) {
	v := m.reg_date
	if v == nil {
		return
	}
	return *v, true
}

// OldRegDate returns the old "reg_date" field's value of the TN_BBS entity.
// If the TN_BBS object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TNBBSMutation) OldRegDate(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRegDate is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRegDate requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRegDate: %w", err)
	}
	return oldValue.RegDate, nil
}

// ResetRegDate resets all changes to the "reg_date" field.
func (m *TNBBSMutation) ResetRegDate() {
	m.reg_date = nil
}

// SetUdtDate sets the "udt_date" field.
func (m *TNBBSMutation) SetUdtDate(s string) {
	m.udt_date = &s
}

// UdtDate returns the value of the "udt_date" field in the mutation.
func (m *TNBBSMutation) UdtDate() (r string, exists bool) {
	v := m.udt_date
	if v == nil {
		return
	}
	return *v, true
}

// OldUdtDate returns the old "udt_date" field's value of the TN_BBS entity.
// If the TN_BBS object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TNBBSMutation) OldUdtDate(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUdtDate is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUdtDate requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUdtDate: %w", err)
	}
	return oldValue.UdtDate, nil
}

// ResetUdtDate resets all changes to the "udt_date" field.
func (m *TNBBSMutation) ResetUdtDate() {
	m.udt_date = nil
}

// Where appends a list predicates to the TNBBSMutation builder.
func (m *TNBBSMutation) Where(ps ...predicate.TN_BBS) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the TNBBSMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *TNBBSMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.TN_BBS, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *TNBBSMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *TNBBSMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (TN_BBS).
func (m *TNBBSMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *TNBBSMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.user_id != nil {
		fields = append(fields, tn_bbs.FieldUserID)
	}
	if m.user_name != nil {
		fields = append(fields, tn_bbs.FieldUserName)
	}
	if m.title != nil {
		fields = append(fields, tn_bbs.FieldTitle)
	}
	if m.content != nil {
		fields = append(fields, tn_bbs.FieldContent)
	}
	if m.delect_yn != nil {
		fields = append(fields, tn_bbs.FieldDelectYn)
	}
	if m.reg_date != nil {
		fields = append(fields, tn_bbs.FieldRegDate)
	}
	if m.udt_date != nil {
		fields = append(fields, tn_bbs.FieldUdtDate)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *TNBBSMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case tn_bbs.FieldUserID:
		return m.UserID()
	case tn_bbs.FieldUserName:
		return m.UserName()
	case tn_bbs.FieldTitle:
		return m.Title()
	case tn_bbs.FieldContent:
		return m.Content()
	case tn_bbs.FieldDelectYn:
		return m.DelectYn()
	case tn_bbs.FieldRegDate:
		return m.RegDate()
	case tn_bbs.FieldUdtDate:
		return m.UdtDate()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *TNBBSMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case tn_bbs.FieldUserID:
		return m.OldUserID(ctx)
	case tn_bbs.FieldUserName:
		return m.OldUserName(ctx)
	case tn_bbs.FieldTitle:
		return m.OldTitle(ctx)
	case tn_bbs.FieldContent:
		return m.OldContent(ctx)
	case tn_bbs.FieldDelectYn:
		return m.OldDelectYn(ctx)
	case tn_bbs.FieldRegDate:
		return m.OldRegDate(ctx)
	case tn_bbs.FieldUdtDate:
		return m.OldUdtDate(ctx)
	}
	return nil, fmt.Errorf("unknown TN_BBS field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TNBBSMutation) SetField(name string, value ent.Value) error {
	switch name {
	case tn_bbs.FieldUserID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserID(v)
		return nil
	case tn_bbs.FieldUserName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserName(v)
		return nil
	case tn_bbs.FieldTitle:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTitle(v)
		return nil
	case tn_bbs.FieldContent:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetContent(v)
		return nil
	case tn_bbs.FieldDelectYn:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDelectYn(v)
		return nil
	case tn_bbs.FieldRegDate:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRegDate(v)
		return nil
	case tn_bbs.FieldUdtDate:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUdtDate(v)
		return nil
	}
	return fmt.Errorf("unknown TN_BBS field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *TNBBSMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *TNBBSMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TNBBSMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown TN_BBS numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *TNBBSMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *TNBBSMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *TNBBSMutation) ClearField(name string) error {
	return fmt.Errorf("unknown TN_BBS nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *TNBBSMutation) ResetField(name string) error {
	switch name {
	case tn_bbs.FieldUserID:
		m.ResetUserID()
		return nil
	case tn_bbs.FieldUserName:
		m.ResetUserName()
		return nil
	case tn_bbs.FieldTitle:
		m.ResetTitle()
		return nil
	case tn_bbs.FieldContent:
		m.ResetContent()
		return nil
	case tn_bbs.FieldDelectYn:
		m.ResetDelectYn()
		return nil
	case tn_bbs.FieldRegDate:
		m.ResetRegDate()
		return nil
	case tn_bbs.FieldUdtDate:
		m.ResetUdtDate()
		return nil
	}
	return fmt.Errorf("unknown TN_BBS field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *TNBBSMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *TNBBSMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *TNBBSMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *TNBBSMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *TNBBSMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *TNBBSMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *TNBBSMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown TN_BBS unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *TNBBSMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown TN_BBS edge %s", name)
}
