// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"goBack/ent/predicate"
	"goBack/ent/tn_bbs"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TNBBSDelete is the builder for deleting a TN_BBS entity.
type TNBBSDelete struct {
	config
	hooks    []Hook
	mutation *TNBBSMutation
}

// Where appends a list predicates to the TNBBSDelete builder.
func (td *TNBBSDelete) Where(ps ...predicate.TN_BBS) *TNBBSDelete {
	td.mutation.Where(ps...)
	return td
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (td *TNBBSDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, td.sqlExec, td.mutation, td.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (td *TNBBSDelete) ExecX(ctx context.Context) int {
	n, err := td.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (td *TNBBSDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(tn_bbs.Table, sqlgraph.NewFieldSpec(tn_bbs.FieldID, field.TypeInt))
	if ps := td.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, td.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	td.mutation.done = true
	return affected, err
}

// TNBBSDeleteOne is the builder for deleting a single TN_BBS entity.
type TNBBSDeleteOne struct {
	td *TNBBSDelete
}

// Where appends a list predicates to the TNBBSDelete builder.
func (tdo *TNBBSDeleteOne) Where(ps ...predicate.TN_BBS) *TNBBSDeleteOne {
	tdo.td.mutation.Where(ps...)
	return tdo
}

// Exec executes the deletion query.
func (tdo *TNBBSDeleteOne) Exec(ctx context.Context) error {
	n, err := tdo.td.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tn_bbs.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tdo *TNBBSDeleteOne) ExecX(ctx context.Context) {
	if err := tdo.Exec(ctx); err != nil {
		panic(err)
	}
}
