// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"goBack/ent/tn_user"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TNUSERCreate is the builder for creating a TN_USER entity.
type TNUSERCreate struct {
	config
	mutation *TNUSERMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (tc *TNUSERCreate) SetUserID(s string) *TNUSERCreate {
	tc.mutation.SetUserID(s)
	return tc
}

// SetUserName sets the "user_name" field.
func (tc *TNUSERCreate) SetUserName(s string) *TNUSERCreate {
	tc.mutation.SetUserName(s)
	return tc
}

// SetPassword sets the "password" field.
func (tc *TNUSERCreate) SetPassword(s string) *TNUSERCreate {
	tc.mutation.SetPassword(s)
	return tc
}

// SetDelectYn sets the "delect_yn" field.
func (tc *TNUSERCreate) SetDelectYn(s string) *TNUSERCreate {
	tc.mutation.SetDelectYn(s)
	return tc
}

// SetRegDate sets the "reg_date" field.
func (tc *TNUSERCreate) SetRegDate(s string) *TNUSERCreate {
	tc.mutation.SetRegDate(s)
	return tc
}

// SetUdtDate sets the "udt_date" field.
func (tc *TNUSERCreate) SetUdtDate(s string) *TNUSERCreate {
	tc.mutation.SetUdtDate(s)
	return tc
}

// SetID sets the "id" field.
func (tc *TNUSERCreate) SetID(i int) *TNUSERCreate {
	tc.mutation.SetID(i)
	return tc
}

// Mutation returns the TNUSERMutation object of the builder.
func (tc *TNUSERCreate) Mutation() *TNUSERMutation {
	return tc.mutation
}

// Save creates the TN_USER in the database.
func (tc *TNUSERCreate) Save(ctx context.Context) (*TN_USER, error) {
	return withHooks(ctx, tc.sqlSave, tc.mutation, tc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TNUSERCreate) SaveX(ctx context.Context) *TN_USER {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *TNUSERCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *TNUSERCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *TNUSERCreate) check() error {
	if _, ok := tc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "TN_USER.user_id"`)}
	}
	if _, ok := tc.mutation.UserName(); !ok {
		return &ValidationError{Name: "user_name", err: errors.New(`ent: missing required field "TN_USER.user_name"`)}
	}
	if _, ok := tc.mutation.Password(); !ok {
		return &ValidationError{Name: "password", err: errors.New(`ent: missing required field "TN_USER.password"`)}
	}
	if _, ok := tc.mutation.DelectYn(); !ok {
		return &ValidationError{Name: "delect_yn", err: errors.New(`ent: missing required field "TN_USER.delect_yn"`)}
	}
	if _, ok := tc.mutation.RegDate(); !ok {
		return &ValidationError{Name: "reg_date", err: errors.New(`ent: missing required field "TN_USER.reg_date"`)}
	}
	if _, ok := tc.mutation.UdtDate(); !ok {
		return &ValidationError{Name: "udt_date", err: errors.New(`ent: missing required field "TN_USER.udt_date"`)}
	}
	return nil
}

func (tc *TNUSERCreate) sqlSave(ctx context.Context) (*TN_USER, error) {
	if err := tc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	tc.mutation.id = &_node.ID
	tc.mutation.done = true
	return _node, nil
}

func (tc *TNUSERCreate) createSpec() (*TN_USER, *sqlgraph.CreateSpec) {
	var (
		_node = &TN_USER{config: tc.config}
		_spec = sqlgraph.NewCreateSpec(tn_user.Table, sqlgraph.NewFieldSpec(tn_user.FieldID, field.TypeInt))
	)
	if id, ok := tc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := tc.mutation.UserID(); ok {
		_spec.SetField(tn_user.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := tc.mutation.UserName(); ok {
		_spec.SetField(tn_user.FieldUserName, field.TypeString, value)
		_node.UserName = value
	}
	if value, ok := tc.mutation.Password(); ok {
		_spec.SetField(tn_user.FieldPassword, field.TypeString, value)
		_node.Password = value
	}
	if value, ok := tc.mutation.DelectYn(); ok {
		_spec.SetField(tn_user.FieldDelectYn, field.TypeString, value)
		_node.DelectYn = value
	}
	if value, ok := tc.mutation.RegDate(); ok {
		_spec.SetField(tn_user.FieldRegDate, field.TypeString, value)
		_node.RegDate = value
	}
	if value, ok := tc.mutation.UdtDate(); ok {
		_spec.SetField(tn_user.FieldUdtDate, field.TypeString, value)
		_node.UdtDate = value
	}
	return _node, _spec
}

// TNUSERCreateBulk is the builder for creating many TN_USER entities in bulk.
type TNUSERCreateBulk struct {
	config
	err      error
	builders []*TNUSERCreate
}

// Save creates the TN_USER entities in the database.
func (tcb *TNUSERCreateBulk) Save(ctx context.Context) ([]*TN_USER, error) {
	if tcb.err != nil {
		return nil, tcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*TN_USER, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TNUSERMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *TNUSERCreateBulk) SaveX(ctx context.Context) []*TN_USER {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *TNUSERCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *TNUSERCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
