// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"goBack/ent/predicate"
	"goBack/ent/tn_user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TNUSERDelete is the builder for deleting a TN_USER entity.
type TNUSERDelete struct {
	config
	hooks    []Hook
	mutation *TNUSERMutation
}

// Where appends a list predicates to the TNUSERDelete builder.
func (td *TNUSERDelete) Where(ps ...predicate.TN_USER) *TNUSERDelete {
	td.mutation.Where(ps...)
	return td
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (td *TNUSERDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, td.sqlExec, td.mutation, td.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (td *TNUSERDelete) ExecX(ctx context.Context) int {
	n, err := td.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (td *TNUSERDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(tn_user.Table, sqlgraph.NewFieldSpec(tn_user.FieldID, field.TypeInt))
	if ps := td.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, td.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	td.mutation.done = true
	return affected, err
}

// TNUSERDeleteOne is the builder for deleting a single TN_USER entity.
type TNUSERDeleteOne struct {
	td *TNUSERDelete
}

// Where appends a list predicates to the TNUSERDelete builder.
func (tdo *TNUSERDeleteOne) Where(ps ...predicate.TN_USER) *TNUSERDeleteOne {
	tdo.td.mutation.Where(ps...)
	return tdo
}

// Exec executes the deletion query.
func (tdo *TNUSERDeleteOne) Exec(ctx context.Context) error {
	n, err := tdo.td.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tn_user.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tdo *TNUSERDeleteOne) ExecX(ctx context.Context) {
	if err := tdo.Exec(ctx); err != nil {
		panic(err)
	}
}
