// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"goBack/ent/predicate"
	"goBack/ent/tn_user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TNUSERUpdate is the builder for updating TN_USER entities.
type TNUSERUpdate struct {
	config
	hooks    []Hook
	mutation *TNUSERMutation
}

// Where appends a list predicates to the TNUSERUpdate builder.
func (tu *TNUSERUpdate) Where(ps ...predicate.TN_USER) *TNUSERUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetUserID sets the "user_id" field.
func (tu *TNUSERUpdate) SetUserID(s string) *TNUSERUpdate {
	tu.mutation.SetUserID(s)
	return tu
}

// SetUserName sets the "user_name" field.
func (tu *TNUSERUpdate) SetUserName(s string) *TNUSERUpdate {
	tu.mutation.SetUserName(s)
	return tu
}

// SetPassword sets the "password" field.
func (tu *TNUSERUpdate) SetPassword(s string) *TNUSERUpdate {
	tu.mutation.SetPassword(s)
	return tu
}

// SetDelectYn sets the "delect_yn" field.
func (tu *TNUSERUpdate) SetDelectYn(s string) *TNUSERUpdate {
	tu.mutation.SetDelectYn(s)
	return tu
}

// SetRegDate sets the "reg_date" field.
func (tu *TNUSERUpdate) SetRegDate(s string) *TNUSERUpdate {
	tu.mutation.SetRegDate(s)
	return tu
}

// SetUdtDate sets the "udt_date" field.
func (tu *TNUSERUpdate) SetUdtDate(s string) *TNUSERUpdate {
	tu.mutation.SetUdtDate(s)
	return tu
}

// Mutation returns the TNUSERMutation object of the builder.
func (tu *TNUSERUpdate) Mutation() *TNUSERMutation {
	return tu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *TNUSERUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, tu.sqlSave, tu.mutation, tu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TNUSERUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TNUSERUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TNUSERUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tu *TNUSERUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(tn_user.Table, tn_user.Columns, sqlgraph.NewFieldSpec(tn_user.FieldID, field.TypeInt))
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.UserID(); ok {
		_spec.SetField(tn_user.FieldUserID, field.TypeString, value)
	}
	if value, ok := tu.mutation.UserName(); ok {
		_spec.SetField(tn_user.FieldUserName, field.TypeString, value)
	}
	if value, ok := tu.mutation.Password(); ok {
		_spec.SetField(tn_user.FieldPassword, field.TypeString, value)
	}
	if value, ok := tu.mutation.DelectYn(); ok {
		_spec.SetField(tn_user.FieldDelectYn, field.TypeString, value)
	}
	if value, ok := tu.mutation.RegDate(); ok {
		_spec.SetField(tn_user.FieldRegDate, field.TypeString, value)
	}
	if value, ok := tu.mutation.UdtDate(); ok {
		_spec.SetField(tn_user.FieldUdtDate, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tn_user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tu.mutation.done = true
	return n, nil
}

// TNUSERUpdateOne is the builder for updating a single TN_USER entity.
type TNUSERUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TNUSERMutation
}

// SetUserID sets the "user_id" field.
func (tuo *TNUSERUpdateOne) SetUserID(s string) *TNUSERUpdateOne {
	tuo.mutation.SetUserID(s)
	return tuo
}

// SetUserName sets the "user_name" field.
func (tuo *TNUSERUpdateOne) SetUserName(s string) *TNUSERUpdateOne {
	tuo.mutation.SetUserName(s)
	return tuo
}

// SetPassword sets the "password" field.
func (tuo *TNUSERUpdateOne) SetPassword(s string) *TNUSERUpdateOne {
	tuo.mutation.SetPassword(s)
	return tuo
}

// SetDelectYn sets the "delect_yn" field.
func (tuo *TNUSERUpdateOne) SetDelectYn(s string) *TNUSERUpdateOne {
	tuo.mutation.SetDelectYn(s)
	return tuo
}

// SetRegDate sets the "reg_date" field.
func (tuo *TNUSERUpdateOne) SetRegDate(s string) *TNUSERUpdateOne {
	tuo.mutation.SetRegDate(s)
	return tuo
}

// SetUdtDate sets the "udt_date" field.
func (tuo *TNUSERUpdateOne) SetUdtDate(s string) *TNUSERUpdateOne {
	tuo.mutation.SetUdtDate(s)
	return tuo
}

// Mutation returns the TNUSERMutation object of the builder.
func (tuo *TNUSERUpdateOne) Mutation() *TNUSERMutation {
	return tuo.mutation
}

// Where appends a list predicates to the TNUSERUpdate builder.
func (tuo *TNUSERUpdateOne) Where(ps ...predicate.TN_USER) *TNUSERUpdateOne {
	tuo.mutation.Where(ps...)
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *TNUSERUpdateOne) Select(field string, fields ...string) *TNUSERUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated TN_USER entity.
func (tuo *TNUSERUpdateOne) Save(ctx context.Context) (*TN_USER, error) {
	return withHooks(ctx, tuo.sqlSave, tuo.mutation, tuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TNUSERUpdateOne) SaveX(ctx context.Context) *TN_USER {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *TNUSERUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TNUSERUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tuo *TNUSERUpdateOne) sqlSave(ctx context.Context) (_node *TN_USER, err error) {
	_spec := sqlgraph.NewUpdateSpec(tn_user.Table, tn_user.Columns, sqlgraph.NewFieldSpec(tn_user.FieldID, field.TypeInt))
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TN_USER.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tn_user.FieldID)
		for _, f := range fields {
			if !tn_user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tn_user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.UserID(); ok {
		_spec.SetField(tn_user.FieldUserID, field.TypeString, value)
	}
	if value, ok := tuo.mutation.UserName(); ok {
		_spec.SetField(tn_user.FieldUserName, field.TypeString, value)
	}
	if value, ok := tuo.mutation.Password(); ok {
		_spec.SetField(tn_user.FieldPassword, field.TypeString, value)
	}
	if value, ok := tuo.mutation.DelectYn(); ok {
		_spec.SetField(tn_user.FieldDelectYn, field.TypeString, value)
	}
	if value, ok := tuo.mutation.RegDate(); ok {
		_spec.SetField(tn_user.FieldRegDate, field.TypeString, value)
	}
	if value, ok := tuo.mutation.UdtDate(); ok {
		_spec.SetField(tn_user.FieldUdtDate, field.TypeString, value)
	}
	_node = &TN_USER{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tn_user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tuo.mutation.done = true
	return _node, nil
}
