// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TnBbSsColumns holds the columns for the "tn_bb_ss" table.
	TnBbSsColumns = []*schema.Column{
		{Name: "idx", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeString},
		{Name: "user_name", Type: field.TypeString},
		{Name: "title", Type: field.TypeString},
		{Name: "content", Type: field.TypeString},
		{Name: "delect_yn", Type: field.TypeString},
		{Name: "reg_date", Type: field.TypeString},
		{Name: "udt_date", Type: field.TypeString},
	}
	// TnBbSsTable holds the schema information for the "tn_bb_ss" table.
	TnBbSsTable = &schema.Table{
		Name:       "tn_bb_ss",
		Columns:    TnBbSsColumns,
		PrimaryKey: []*schema.Column{TnBbSsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TnBbSsTable,
	}
)

func init() {
}
