// Code generated by ent, DO NOT EDIT.

package tn_bbs

import (
	"goBack/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldEQ(FieldUserID, v))
}

// UserName applies equality check predicate on the "user_name" field. It's identical to UserNameEQ.
func UserName(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldEQ(FieldUserName, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldEQ(FieldTitle, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldEQ(FieldContent, v))
}

// DelectYn applies equality check predicate on the "delect_yn" field. It's identical to DelectYnEQ.
func DelectYn(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldEQ(FieldDelectYn, v))
}

// RegDate applies equality check predicate on the "reg_date" field. It's identical to RegDateEQ.
func RegDate(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldEQ(FieldRegDate, v))
}

// UdtDate applies equality check predicate on the "udt_date" field. It's identical to UdtDateEQ.
func UdtDate(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldEQ(FieldUdtDate, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldContainsFold(FieldUserID, v))
}

// UserNameEQ applies the EQ predicate on the "user_name" field.
func UserNameEQ(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldEQ(FieldUserName, v))
}

// UserNameNEQ applies the NEQ predicate on the "user_name" field.
func UserNameNEQ(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldNEQ(FieldUserName, v))
}

// UserNameIn applies the In predicate on the "user_name" field.
func UserNameIn(vs ...string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldIn(FieldUserName, vs...))
}

// UserNameNotIn applies the NotIn predicate on the "user_name" field.
func UserNameNotIn(vs ...string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldNotIn(FieldUserName, vs...))
}

// UserNameGT applies the GT predicate on the "user_name" field.
func UserNameGT(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldGT(FieldUserName, v))
}

// UserNameGTE applies the GTE predicate on the "user_name" field.
func UserNameGTE(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldGTE(FieldUserName, v))
}

// UserNameLT applies the LT predicate on the "user_name" field.
func UserNameLT(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldLT(FieldUserName, v))
}

// UserNameLTE applies the LTE predicate on the "user_name" field.
func UserNameLTE(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldLTE(FieldUserName, v))
}

// UserNameContains applies the Contains predicate on the "user_name" field.
func UserNameContains(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldContains(FieldUserName, v))
}

// UserNameHasPrefix applies the HasPrefix predicate on the "user_name" field.
func UserNameHasPrefix(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldHasPrefix(FieldUserName, v))
}

// UserNameHasSuffix applies the HasSuffix predicate on the "user_name" field.
func UserNameHasSuffix(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldHasSuffix(FieldUserName, v))
}

// UserNameEqualFold applies the EqualFold predicate on the "user_name" field.
func UserNameEqualFold(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldEqualFold(FieldUserName, v))
}

// UserNameContainsFold applies the ContainsFold predicate on the "user_name" field.
func UserNameContainsFold(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldContainsFold(FieldUserName, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldContainsFold(FieldTitle, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldContainsFold(FieldContent, v))
}

// DelectYnEQ applies the EQ predicate on the "delect_yn" field.
func DelectYnEQ(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldEQ(FieldDelectYn, v))
}

// DelectYnNEQ applies the NEQ predicate on the "delect_yn" field.
func DelectYnNEQ(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldNEQ(FieldDelectYn, v))
}

// DelectYnIn applies the In predicate on the "delect_yn" field.
func DelectYnIn(vs ...string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldIn(FieldDelectYn, vs...))
}

// DelectYnNotIn applies the NotIn predicate on the "delect_yn" field.
func DelectYnNotIn(vs ...string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldNotIn(FieldDelectYn, vs...))
}

// DelectYnGT applies the GT predicate on the "delect_yn" field.
func DelectYnGT(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldGT(FieldDelectYn, v))
}

// DelectYnGTE applies the GTE predicate on the "delect_yn" field.
func DelectYnGTE(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldGTE(FieldDelectYn, v))
}

// DelectYnLT applies the LT predicate on the "delect_yn" field.
func DelectYnLT(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldLT(FieldDelectYn, v))
}

// DelectYnLTE applies the LTE predicate on the "delect_yn" field.
func DelectYnLTE(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldLTE(FieldDelectYn, v))
}

// DelectYnContains applies the Contains predicate on the "delect_yn" field.
func DelectYnContains(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldContains(FieldDelectYn, v))
}

// DelectYnHasPrefix applies the HasPrefix predicate on the "delect_yn" field.
func DelectYnHasPrefix(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldHasPrefix(FieldDelectYn, v))
}

// DelectYnHasSuffix applies the HasSuffix predicate on the "delect_yn" field.
func DelectYnHasSuffix(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldHasSuffix(FieldDelectYn, v))
}

// DelectYnEqualFold applies the EqualFold predicate on the "delect_yn" field.
func DelectYnEqualFold(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldEqualFold(FieldDelectYn, v))
}

// DelectYnContainsFold applies the ContainsFold predicate on the "delect_yn" field.
func DelectYnContainsFold(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldContainsFold(FieldDelectYn, v))
}

// RegDateEQ applies the EQ predicate on the "reg_date" field.
func RegDateEQ(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldEQ(FieldRegDate, v))
}

// RegDateNEQ applies the NEQ predicate on the "reg_date" field.
func RegDateNEQ(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldNEQ(FieldRegDate, v))
}

// RegDateIn applies the In predicate on the "reg_date" field.
func RegDateIn(vs ...string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldIn(FieldRegDate, vs...))
}

// RegDateNotIn applies the NotIn predicate on the "reg_date" field.
func RegDateNotIn(vs ...string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldNotIn(FieldRegDate, vs...))
}

// RegDateGT applies the GT predicate on the "reg_date" field.
func RegDateGT(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldGT(FieldRegDate, v))
}

// RegDateGTE applies the GTE predicate on the "reg_date" field.
func RegDateGTE(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldGTE(FieldRegDate, v))
}

// RegDateLT applies the LT predicate on the "reg_date" field.
func RegDateLT(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldLT(FieldRegDate, v))
}

// RegDateLTE applies the LTE predicate on the "reg_date" field.
func RegDateLTE(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldLTE(FieldRegDate, v))
}

// RegDateContains applies the Contains predicate on the "reg_date" field.
func RegDateContains(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldContains(FieldRegDate, v))
}

// RegDateHasPrefix applies the HasPrefix predicate on the "reg_date" field.
func RegDateHasPrefix(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldHasPrefix(FieldRegDate, v))
}

// RegDateHasSuffix applies the HasSuffix predicate on the "reg_date" field.
func RegDateHasSuffix(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldHasSuffix(FieldRegDate, v))
}

// RegDateEqualFold applies the EqualFold predicate on the "reg_date" field.
func RegDateEqualFold(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldEqualFold(FieldRegDate, v))
}

// RegDateContainsFold applies the ContainsFold predicate on the "reg_date" field.
func RegDateContainsFold(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldContainsFold(FieldRegDate, v))
}

// UdtDateEQ applies the EQ predicate on the "udt_date" field.
func UdtDateEQ(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldEQ(FieldUdtDate, v))
}

// UdtDateNEQ applies the NEQ predicate on the "udt_date" field.
func UdtDateNEQ(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldNEQ(FieldUdtDate, v))
}

// UdtDateIn applies the In predicate on the "udt_date" field.
func UdtDateIn(vs ...string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldIn(FieldUdtDate, vs...))
}

// UdtDateNotIn applies the NotIn predicate on the "udt_date" field.
func UdtDateNotIn(vs ...string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldNotIn(FieldUdtDate, vs...))
}

// UdtDateGT applies the GT predicate on the "udt_date" field.
func UdtDateGT(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldGT(FieldUdtDate, v))
}

// UdtDateGTE applies the GTE predicate on the "udt_date" field.
func UdtDateGTE(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldGTE(FieldUdtDate, v))
}

// UdtDateLT applies the LT predicate on the "udt_date" field.
func UdtDateLT(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldLT(FieldUdtDate, v))
}

// UdtDateLTE applies the LTE predicate on the "udt_date" field.
func UdtDateLTE(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldLTE(FieldUdtDate, v))
}

// UdtDateContains applies the Contains predicate on the "udt_date" field.
func UdtDateContains(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldContains(FieldUdtDate, v))
}

// UdtDateHasPrefix applies the HasPrefix predicate on the "udt_date" field.
func UdtDateHasPrefix(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldHasPrefix(FieldUdtDate, v))
}

// UdtDateHasSuffix applies the HasSuffix predicate on the "udt_date" field.
func UdtDateHasSuffix(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldHasSuffix(FieldUdtDate, v))
}

// UdtDateEqualFold applies the EqualFold predicate on the "udt_date" field.
func UdtDateEqualFold(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldEqualFold(FieldUdtDate, v))
}

// UdtDateContainsFold applies the ContainsFold predicate on the "udt_date" field.
func UdtDateContainsFold(v string) predicate.TN_BBS {
	return predicate.TN_BBS(sql.FieldContainsFold(FieldUdtDate, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TN_BBS) predicate.TN_BBS {
	return predicate.TN_BBS(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TN_BBS) predicate.TN_BBS {
	return predicate.TN_BBS(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TN_BBS) predicate.TN_BBS {
	return predicate.TN_BBS(sql.NotPredicates(p))
}
